### ISSUE TITLE
Access denied on S3 to Quickstart utility

### ISSUE THREAD

**Issue by armitagemderivitec** [aws-quickstart/quickstart-microsoft-rdgateway#17]
I'm using an item at the following location in my LaunchConfiguration:

https://s3.amazonaws.com/quickstart-reference/microsoft/rdgateway/latest/submodules/quickstart-microsoft-utilities/modules/AWSQuickStart.zip

Suddenly I am getting access denied. Is this expected?

**Comment by vsnyc** [comment]
The new link is:
https://s3.amazonaws.com/aws-quickstart/quickstart-microsoft-rdgateway/submodules/quickstart-microsoft-utilities/modules/AWSQuickStart.zip

In general we migrated the production location of the AWS Quick Starts from quickstart-reference S3 bucket to aws-quickstart bucket and changed the prefix at which the assets reside making it simpler to map from github to S3.

In the new structure, any aws-quickstart repository is copied to the S3 prefix that matches name of the repository. In this case, all content of `quickstart-microsoft-rdgateway` repository is uploaded `s3://aws-quickstart/quickstart-microsoft-rdgateway`.

**Comment by RobBiddle** [comment]
Not cool.

All of our Windows EC2 templates were using https://s3.amazonaws.com/quickstart-reference/microsoft/utilities/latest/modules/AWSQuickStart.zip which apparently also got axed.

My bad for expecting AWS to maintain those buckets, but still not cool.  The Quickstart docs should state that those resources should be moved to user controlled buckets if they're subject to being killed off.

**Comment by armitagemderivitec** [comment]
Thanks @vsnyc, for me I realised that any dependency for our systems builds should be hosted in our own buckets and I have adjusted them accordingly. Thanks for the quick response.

**Comment by vsnyc** [comment]
@RobBiddle sincere apologies for the inconvenience. We did allow for roughly one year of keeping content in both buckets to ease the migration. The links on the Quick Start pages have been pointing to the new aws-quickstart bucket since May 2018, so you must have had the links from before. As I mentioned above, the content has been moved in a new `aws-quickstart` bucket in a manner that is easier to discover. That is, anything in this git repo can be found at `s3://aws-quickstart/quickstart-microsoft-rdgateway/`. We did this so the aws-quickstart org repositories and contents in the `aws-quickstart` bucket are kept in sync.
